esphome:
  name: si1151-0
  friendly_name: Sunlight Sensor

external_components:
  - source: github://jduanen/ESPHomeComponents
    components: [ Si1151 ]

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: arduino
    version: latest
    platform_version: 6.3.2

logger:
  level: VERBOSE

api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Sunlight Sensor Fallback Hotspot"
    password: !secret wifi_ap_password

captive_portal:

i2c:
    sda: GPIO6
    scl: GPIO7
    scan: true
    frequency: 400kHz

sensor:
  - platform: Si1151
    infrared_channel:
      name: "Sunlight IR"
    visible_channel:
      name: "Sunlight Visible"
    uv_channel:
      name: "Sunlight UV"
