esphome:
  name: si1151-0
  friendly_name: Sunlight Sensor
  includes:
    - Si1151.h
  libraries:
    - "Si115X"

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: arduino
    version: latest
    platform_version: 6.3.2

logger:
  level: VERBOSE

api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Sunlight Sensor Fallback Hotspot"
    password: !secret wifi_ap_password

captive_portal:

i2c:
    sda: GPIO6
    scl: GPIO7
    scan: true
    frequency: 800kHz

##      Si1151 *light_sensor = new Si1151();

sensor:
  - platform: custom
    lambda: |-
      Si1151 *light_sensor = new Si1151();
      App.register_component(light_sensor);
      return {light_sensor};
    sensors:
      - name: "Sunlight IR"
        id: sunlight_ir
#        unit_of_measurement: ?
#        accuracy_decimals: 2
      - name: "Sunlight Visible"
        id: sunlight_visible
#        unit_of_measurement: ?
#        accuracy_decimals: 2
      - name: "Sunlight UV"
        id: sunlight_uv
#        unit_of_measurement: ?
#        accuracy_decimals: 2
